### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by zakizakinozaki** [zakizakinozaki/furima-34440#10]
自身のフリマアプリのURL
https://furima-34440.herokuapp.com/

Basic認証のIDとパスワード
ID:crypto
PW:4274

出品者用のメールアドレスとパスワード
アドレス:test@test
PW:1a1a1a

購入者用のメールアドレスとパスワード
アドレス:test2@test
PW:1a1a1a

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀
![最終課題終了_おめでとう画像3](https://user-images.githubusercontent.com/49669977/109446150-7c066e00-7a84-11eb-8ba3-3facfe6cba91.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
